language: node_js
node_js:
    - 12

services:
  - docker

before_install:
  #install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - docker build -t registry.heroku.com/scotccc/web .

deploy:
  provider: script
  script:
    bash docker_push
  on:
    branch: scotty_ccc

# safelist
branches:
  only:
  - scotty_ccc
