language: node_js
node_js:
    - 12

install: true

before_script:
  - npm install -g jest
script:
  - yarn run test

# safelist
branches:
  only:
  - master
  - scotty_aaa
  - scotty_actnearn
  - scotty_bloque64
  - scotty_pal
  - scotty_spt
  - scotty_steemcoinpan
  - scotty_weedcash
